version: "3.7"
services:
  node:
    build:
      context: ./
      target: build-stage
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    command: ["npm", "run", "dev"]
