version: "3.7"
services:
    web:
        image: nginx:1.16.1-alpine
        volumes:
         - ./:/usr/share/nginx/html/www
        ports:
         - "8080:80"
        environment:
         - NGINX_HOST=foobar.com
         - NGINX_PORT=80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"