version: "3.7"
services:
  web:
    image: nginx:1.16.1-alpine
    volumes:
      - ./www.conf:/etc/nginx/conf.d/www.conf
      - ./index.html:/usr/share/nginx/html/www/index.html
    ports:
      - "80:80"